// Secrets aren't declared in wrangler.toml, so `wrangler types` can't see them.
// Merge them (and the about-editor bindings/vars below) into both the global `Env`
// (what the worker code uses) and `Cloudflare.Env` (what `cloudflare:test`'s `env` /
// `ProvidedEnv` extend), so they're visible in both the worker and the tests.
//
// The about editor's `[vars]` (GITHUB_OWNER/REPO/BRANCH, ABOUT_MD_PATH,
// R2_PUBLIC_BASE_URL) are also generated by `wrangler types`; they're declared here
// too so the build/tests don't depend on regenerating worker-configuration.d.ts.
// The ABOUT_BUCKET binding is commented out in wrangler.toml until the R2 bucket is
// provisioned, so it's optional and declared only here.
interface Env {
  /** Resend API key. Set with `wrangler secret put RESEND_API_KEY`. */
  RESEND_API_KEY: string;
  /**
   * HMAC key(s) signing the one-click unsubscribe tokens, comma-separated (sign with
   * the first, verify against all — that's the rotation story). Rotate by *prepending*
   * the new secret and deploying. The list is **append-only: never prune by default** —
   * the tokens have no expiry and ride in mail people keep forever, so dropping a secret
   * permanently breaks the unsubscribe link in every message signed with it (the spam
   * report this feature exists to prevent), while keeping one costs a single extra
   * `crypto.subtle.verify`. If one ever must go (compromise), the hard floor is **24
   * months** after the last send that used it. Set with
   * `wrangler secret put UNSUBSCRIBE_SECRET`.
   */
  UNSUBSCRIBE_SECRET: string;
  /**
   * HMAC key(s) signing the emailed "I've memorized this" links (comma-separated;
   * sign with the first, verify against all). Rotate by prepending. Must be the SAME
   * value as apps/login's — this worker mints the tokens, that one verifies them when
   * minting a session.
   *
   * The retention policy is the **opposite** of `UNSUBSCRIBE_SECRET`'s. These tokens
   * expire 30 days after their send, and for their first 7 days one is a login
   * credential — so a retired secret is **prunable** once its tokens are all dead
   * (floor: 60 days after its last send), and if one is ever suspected of leaking,
   * removing it is the correct incident response, not the harm: it revokes every
   * outstanding link in a single deploy, and the worst outcome is a dead button. Set
   * with `wrangler secret put MEMORIZED_SECRET` (on **both** workers).
   */
  MEMORIZED_SECRET: string;
  /** GitHub PAT (contents:write on whyredevprojects/mishna). Set with `wrangler secret put GITHUB_TOKEN`. */
  GITHUB_TOKEN: string;
  /** GitHub repo owner for the about commit (wrangler.toml [vars]). */
  GITHUB_OWNER: string;
  /** GitHub repo name for the about commit (wrangler.toml [vars]). */
  GITHUB_REPO: string;
  /** Branch the about.md commit targets, e.g. "main" (wrangler.toml [vars]). */
  GITHUB_BRANCH: string;
  /** Monorepo-relative path to the English about Markdown the www site renders (wrangler.toml [vars]). */
  ABOUT_MD_PATH: string;
  /** Monorepo-relative path to the Hebrew about Markdown the www site renders (wrangler.toml [vars]). */
  ABOUT_MD_PATH_HE: string;
  /** Public base URL of the R2 bucket serving about images (wrangler.toml [vars]). */
  R2_PUBLIC_BASE_URL: string;
  /** R2 bucket for about-editor images. Optional until the bucket is provisioned. */
  ABOUT_BUCKET?: R2Bucket;
}

declare namespace Cloudflare {
  interface Env {
    /** Resend API key. Set with `wrangler secret put RESEND_API_KEY`. */
    RESEND_API_KEY: string;
    /**
     * HMAC key(s) for the one-click unsubscribe tokens (comma-separated; sign with the
     * first, verify against all). Rotate by prepending. The list is **append-only:
     * never prune by default** — the tokens never expire and ride in mail people keep
     * forever, so removing a secret kills the unsubscribe link in every message signed
     * with it. Hard floor if one ever must go: **24 months** after its last send.
     */
    UNSUBSCRIBE_SECRET: string;
    /**
     * HMAC key(s) signing the emailed "I've memorized this" links (comma-separated;
     * sign with the first, verify against all). Same value as apps/login's. Unlike
     * `UNSUBSCRIBE_SECRET` this list is **prunable and revocable** — its tokens expire
     * in 30 days, and one is a login credential for its first 7, so dropping a leaked
     * secret is the incident response rather than the harm.
     */
    MEMORIZED_SECRET: string;
    /** GitHub PAT (contents:write on whyredevprojects/mishna). Set with `wrangler secret put GITHUB_TOKEN`. */
    GITHUB_TOKEN: string;
    /** GitHub repo owner for the about commit (wrangler.toml [vars]). */
    GITHUB_OWNER: string;
    /** GitHub repo name for the about commit (wrangler.toml [vars]). */
    GITHUB_REPO: string;
    /** Branch the about.md commit targets, e.g. "main" (wrangler.toml [vars]). */
    GITHUB_BRANCH: string;
    /** Monorepo-relative path to the about Markdown the www site renders (wrangler.toml [vars]). */
    ABOUT_MD_PATH: string;
    /** Public base URL of the R2 bucket serving about images (wrangler.toml [vars]). */
    R2_PUBLIC_BASE_URL: string;
    /** R2 bucket for about-editor images. Optional until the bucket is provisioned. */
    ABOUT_BUCKET?: R2Bucket;
  }
}
