// Secrets aren't declared in wrangler.toml, so `wrangler types` can't see them.
// Merge them (and the about-editor bindings/vars below) into both the global `Env`
// (what the worker code uses) and `Cloudflare.Env` (what `cloudflare:test`'s `env` /
// `ProvidedEnv` extend), so they're visible in both the worker and the tests.
//
// The about editor's `[vars]` (GITHUB_OWNER/REPO/BRANCH, ABOUT_MD_PATH,
// R2_PUBLIC_BASE_URL) are also generated by `wrangler types`; they're declared here
// too so the build/tests don't depend on regenerating worker-configuration.d.ts.
// The ABOUT_BUCKET binding is commented out in wrangler.toml until the R2 bucket is
// provisioned, so it's optional and declared only here.
interface Env {
  /** Resend API key. Set with `wrangler secret put RESEND_API_KEY`. */
  RESEND_API_KEY: string;
  /** GitHub PAT (contents:write on whyredevprojects/mishna). Set with `wrangler secret put GITHUB_TOKEN`. */
  GITHUB_TOKEN: string;
  /** GitHub repo owner for the about commit (wrangler.toml [vars]). */
  GITHUB_OWNER: string;
  /** GitHub repo name for the about commit (wrangler.toml [vars]). */
  GITHUB_REPO: string;
  /** Branch the about.md commit targets, e.g. "main" (wrangler.toml [vars]). */
  GITHUB_BRANCH: string;
  /** Monorepo-relative path to the about Markdown the www site renders (wrangler.toml [vars]). */
  ABOUT_MD_PATH: string;
  /** Public base URL of the R2 bucket serving about images (wrangler.toml [vars]). */
  R2_PUBLIC_BASE_URL: string;
  /** R2 bucket for about-editor images. Optional until the bucket is provisioned. */
  ABOUT_BUCKET?: R2Bucket;
}

declare namespace Cloudflare {
  interface Env {
    /** Resend API key. Set with `wrangler secret put RESEND_API_KEY`. */
    RESEND_API_KEY: string;
    /** GitHub PAT (contents:write on whyredevprojects/mishna). Set with `wrangler secret put GITHUB_TOKEN`. */
    GITHUB_TOKEN: string;
    /** GitHub repo owner for the about commit (wrangler.toml [vars]). */
    GITHUB_OWNER: string;
    /** GitHub repo name for the about commit (wrangler.toml [vars]). */
    GITHUB_REPO: string;
    /** Branch the about.md commit targets, e.g. "main" (wrangler.toml [vars]). */
    GITHUB_BRANCH: string;
    /** Monorepo-relative path to the about Markdown the www site renders (wrangler.toml [vars]). */
    ABOUT_MD_PATH: string;
    /** Public base URL of the R2 bucket serving about images (wrangler.toml [vars]). */
    R2_PUBLIC_BASE_URL: string;
    /** R2 bucket for about-editor images. Optional until the bucket is provisioned. */
    ABOUT_BUCKET?: R2Bucket;
  }
}
