/**
 * English (transliterated) mesechta name → Hebrew name, for rendering refs
 * whose \`mesechta\` comes from the API in English. Generated from
 * libs/shared/domain mishnahDataset; kept exhaustive by
 * mesechta-hebrew-names.spec.ts.
 */
export const MESECHTA_HEBREW_NAMES: Record<string, string> = {
  "Berakhot": "ברכות",
  "Peah": "פאה",
  "Demai": "דמאי",
  "Kilayim": "כלאים",
  "Sheviit": "שביעית",
  "Terumot": "תרומות",
  "Maasrot": "מעשרות",
  "Maaser Sheni": "מעשר שני",
  "Challah": "חלה",
  "Orlah": "ערלה",
  "Bikkurim": "ביכורים",
  "Shabbat": "שבת",
  "Eruvin": "עירובין",
  "Pesachim": "פסחים",
  "Shekalim": "שקלים",
  "Yoma": "יומא",
  "Sukkah": "סוכה",
  "Beitzah": "ביצה",
  "Rosh Hashanah": "ראש השנה",
  "Ta'anit": "תענית",
  "Megillah": "מגילה",
  "Moed Katan": "מועד קטן",
  "Chagigah": "חגיגה",
  "Yevamot": "יבמות",
  "Ketubot": "כתובות",
  "Nedarim": "נדרים",
  "Nazir": "נזיר",
  "Sotah": "סוטה",
  "Gittin": "גיטין",
  "Kiddushin": "קידושין",
  "Bava Kamma": "בבא קמא",
  "Bava Metzia": "בבא מציעא",
  "Bava Batra": "בבא בתרא",
  "Sanhedrin": "סנהדרין",
  "Makkot": "מכות",
  "Shevuot": "שבועות",
  "Eduyot": "עדיות",
  "Avodah Zarah": "עבודה זרה",
  "Pirkei Avot": "אבות",
  "Horayot": "הוריות",
  "Zevachim": "זבחים",
  "Menachot": "מנחות",
  "Chullin": "חולין",
  "Bekhorot": "בכורות",
  "Arakhin": "ערכין",
  "Temurah": "תמורה",
  "Keritot": "כריתות",
  "Meilah": "מעילה",
  "Tamid": "תמיד",
  "Middot": "מדות",
  "Kinnim": "קינים",
  "Kelim": "כלים",
  "Oholot": "אהלות",
  "Negaim": "נגעים",
  "Parah": "פרה",
  "Tahorot": "טהרות",
  "Mikvaot": "מקואות",
  "Niddah": "נדה",
  "Makhshirin": "מכשירין",
  "Zavim": "זבים",
  "Tevul Yom": "טבול יום",
  "Yadayim": "ידים",
  "Oktzin": "עוקצים",
};
